monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!websocketserver"]
        websocketserver:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.websocketserver.log"
            level: debug
            channels: ["websocketserver"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
